# Config file for Air in TOML format

[build]
  # The command to build your project. This builds the project and outputs the binary to the tmp directory.
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  log = "tmp/build-errors.log"


[watch]
  # List of file extensions to watch for changes.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # List of directories to watch for changes.
  dirs = ["src"]
  # Exclude tmp directory from watching to prevent infinite loops.
  exclude_dir = ["tmp"]
  # Delay between file change detection and server restart.
  delay = 1000

[logger]
  # Log file for air runtime errors.
  filename = "tmp/air.log"
  # Logging level.
  level = "debug"

[check]
  # URLs to check after the server is restarted.
  urls = ["http://127.0.0.1:3000"]
